# Generated by Django 6.0.3 on 2026-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0004_alter_mediaasset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='static_image',
            fields=[
                ('static_image_id', models.AutoField(primary_key=True)),
                ('label', models.TextField()),
                ('media_asset', models.ForeignKey('media.MediaAsset', on_delete=models.SET_NULL, blank=True, null=True)),
            ],
        ),
    ]
