# Generated by Django 6.0.3 on 2026-04-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0004_alter_mediaasset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticImage',
            fields=[
                ('static_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'Static Image',
                'verbose_name_plural': 'Static Images',
                'db_table': 'static_image',
                'ordering': ['static_image_id'],
            },
        ),
    ]
