# Generated by Django 6.0.3 on 2026-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='static_image',
            options={'ordering': ['static_image_id'], 'verbose_name': 'Static Image', 'verbose_name_plural': 'Static Images'},
        ),
        migrations.AlterField(
            model_name='static_image',
            name='static_image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='static_image',
            table='static_image',
        ),
    ]
