# Generated by Django 6.0.3 on 2026-09-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_consolidate_media_and_static_image'),
        ('static_image', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='StaticImage',
                ),
            ],
        ),
    ]
