# Generated by Django 6.0.3 on 2026-04-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
    ]
