# Generated by Django 6.0.3 on 2026-04-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_media_asset_id_event_media_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
