# Generated by Django 6.0.3 on 2026-09-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_calendar_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='location_en',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='event',
            name='description_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ja',
            field=models.TextField(blank=True),
        ),
    ]
