# Generated by Django 6.0.3 on 2026-09-06 17:04

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_description_event_description_en_and_more'),
        ('volunteer_slots', '0002_remove_volunteerslot_state'),
        ('volunteer_signup', '0004_remove_volunteersignup_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='VolunteerSlot',
                    fields=[
                        ('volunteer_slot_id', models.AutoField(primary_key=True, serialize=False)),
                        ('position_name', models.CharField(max_length=255)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('start_datetime', models.DateTimeField()),
                        ('end_datetime', models.DateTimeField()),
                        ('capacity', models.IntegerField(default=1)),
                        ('filled_count', models.IntegerField(default=0)),
                        ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
                    ],
                    options={
                        'db_table': 'volunteer_slots',
                    },
                ),
                migrations.CreateModel(
                    name='VolunteerSignup',
                    fields=[
                        ('volunteer_signup_id', models.AutoField(primary_key=True, serialize=False)),
                        ('first_name', models.CharField(max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone', models.CharField(max_length=20)),
                        ('status', models.CharField(default='pending', max_length=50)),
                        ('submitted_at', models.DateTimeField(auto_now_add=True)),
                        ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='events.volunteerslot')),
                    ],
                    options={
                        'db_table': 'volunteer_signup',
                    },
                ),
            ],
        ),
    ]
