# Generated by Django 6.0.3 on 2026-09-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_consolidate_volunteer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.TextField(blank=True),
        ),
    ]
