# Generated by Django 6.0.3 on 2026-09-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_location_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='send_volunteer_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
