# Generated by Django 6.0.3 on 2026-10-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_add_event_reminder_fields"),
        ("media", "0006_consolidate_media_and_static_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "event_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("caption_en", models.TextField(blank=True)),
                ("caption_ja", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "image_width",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (25, "25%"),
                            (50, "50%"),
                            (75, "75%"),
                            (100, "100%"),
                        ],
                        default=100,
                    ),
                ),
                (
                    "image_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=6,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="events.event",
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_images",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Images",
                "db_table": "event_image",
                "ordering": ["event", "display_order", "event_image_id"],
            },
        ),
    ]
