# Generated by Django 6.0.3 on 2026-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteersignup',
            name='status',
            field=models.CharField(default='approved', max_length=50),
        ),
    ]
