# Generated by Django 6.0.3 on 2026-04-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer_signup', '0001_initial'),
        ('volunteer_slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersignup',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='volunteer_slots.volunteerslot'),
        ),
    ]
