# Generated by Django 6.0.3 on 2026-04-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_signup', '0002_initial'),
        ('volunteer_slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteersignup',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='volunteer_slots.volunteerslot'),
        ),
    ]
