# Generated by Django 6.0.3 on 2026-04-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0004_alter_mediaasset_file'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(max_length=255)),
                ('content_en', models.TextField(blank=True)),
                ('content_ja', models.TextField(blank=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaasset')),
                ('page_id', models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.page')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'content',
                'ordering': ['page_id', 'content_id'],
            },
        ),
    ]
