# Generated by Django 6.0.3 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_content_image_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="image_width",
            field=models.PositiveSmallIntegerField(
                choices=[(25, "25%"), (50, "50%"), (75, "75%"), (100, "100%")],
                default=100,
            ),
        ),
    ]
