# Generated by Django 6.0.3 on 2026-09-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date', '-created_at', 'donation_id'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-start_date', '-created_at', 'membership_id'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
    ]
