# Generated by Django 6.0.3 on 2026-10-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_admin_table_revision_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='checkout_reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_option_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
