# Generated by Django 6.0.3 on 2026-04-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('board_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('media_asset_id', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.TextField()),
                ('start_date', models.DateField()),
                ('caption', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'db_table': 'board_member',
                'ordering': ['display_order', 'board_member_id'],
            },
        ),
    ]
