# Generated by Django 6.0.3 on 2026-04-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_members', '0001_initial'),
        ('media', '0004_alter_mediaasset_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='media_asset_id',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaasset'),
        ),
    ]
