# Generated by Django 6.0.3 on 2026-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_members', '0002_remove_boardmember_media_asset_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='caption',
            new_name='caption_en',
        ),
        migrations.RenameField(
            model_name='boardmember',
            old_name='display_name',
            new_name='display_name_en',
        ),
        migrations.RenameField(
            model_name='boardmember',
            old_name='role',
            new_name='role_en',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='caption_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='display_name_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='role_ja',
            field=models.TextField(blank=True),
        ),
    ]
