# Generated by Django 6.0.3 on 2026-04-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_calendar_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSlot',
            fields=[
                ('volunteer_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('filled_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
            ],
            options={
                'db_table': 'volunteer_slots',
            },
        ),
    ]
