# Generated by Django 6.0.3 on 2026-04-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-is_executive', 'created_at', 'last_name', 'first_name'], 'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
    ]
