# Generated by Django 6.0.3 on 2026-04-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partner',
            table='partner',
        ),
    ]
