# Generated by Django 6.0.3 on 2026-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_partner_media_asset_id_partner_media_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='category',
            new_name='category_en',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='display_name',
            new_name='display_name_en',
        ),
        migrations.AddField(
            model_name='partner',
            name='category_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='display_name_ja',
            field=models.TextField(blank=True),
        ),
    ]
