# Generated by Django 6.0.3 on 2026-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediaasset_delete_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to='public/'),
        ),
    ]
