# Generated by Django 6.0.3 on 2026-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaasset_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaasset',
            old_name='alt_text',
            new_name='alt_text_en',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='alt_text_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
