# Generated by Django 6.0.3 on 2026-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_title',
            new_name='page_title_en',
        ),
        migrations.AddField(
            model_name='page',
            name='page_title_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
